"""Operator login and role checks (brief §18: restrict sensitive operator actions).

Two users come from the environment (generated by `make .env`, never hard-coded):
`operator` may approve allocations; `admin` may also inject resilience-demo failures.
Reading the dashboard stays open. Tokens are HS256 JWTs signed with JWT_SECRET.
"""

from __future__ import annotations

import hmac
from datetime import UTC, datetime, timedelta
from typing import Any, Literal

import jwt
import structlog
from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field

log = structlog.get_logger()

Role = Literal["operator", "admin"]
RANK = {"operator": 1, "admin": 2}
TOKEN_TTL = timedelta(hours=8)


class LoginBody(BaseModel):
    username: str = Field(min_length=1, max_length=64, pattern=r"^[A-Za-z0-9_.-]+$")
    password: str = Field(min_length=1, max_length=256)


class User(BaseModel):
    username: str
    role: Role


class Auth:
    def __init__(self, secret: str, users: dict[str, tuple[str, Role]]) -> None:
        self.secret = secret
        self.users = users  # username -> (password, role)

    def login(self, body: LoginBody) -> dict[str, Any]:
        entry = self.users.get(body.username)
        # compare against a dummy on unknown users so timing does not reveal valid names
        expected = entry[0] if entry else "x" * 32
        if not hmac.compare_digest(body.password.encode(), expected.encode()) or entry is None:
            log.warning("auth.login_failed", username=body.username)
            raise HTTPException(401, "invalid username or password")
        role = entry[1]
        exp = datetime.now(UTC) + TOKEN_TTL
        token = jwt.encode({"sub": body.username, "role": role, "exp": exp}, self.secret, "HS256")
        log.info("auth.login", username=body.username, role=role)
        return {"token": token, "username": body.username, "role": role, "expires_at": exp}

    def user_from(self, request: Request) -> User | None:
        header = request.headers.get("authorization", "")
        if not header.lower().startswith("bearer "):
            return None
        try:
            claims = jwt.decode(header[7:], self.secret, algorithms=["HS256"])
        except jwt.InvalidTokenError:  # includes ExpiredSignatureError
            return None
        if claims.get("role") not in RANK:
            return None
        return User(username=str(claims["sub"]), role=claims["role"])

    def require(self, role: Role) -> Any:
        def dependency(request: Request) -> User:
            user = self.user_from(request)
            if user is None:
                raise HTTPException(401, "login required", headers={"WWW-Authenticate": "Bearer"})
            if RANK[user.role] < RANK[role]:
                raise HTTPException(403, f"{role} role required")
            return user

        return Depends(dependency)


def auth_router(auth: Auth) -> APIRouter:
    r = APIRouter(prefix="/api/v1/auth")

    @r.post("/login")
    def login(body: LoginBody) -> dict[str, Any]:
        return auth.login(body)

    operator = auth.require("operator")

    @r.get("/me")
    def me(user: User = operator) -> User:
        return user

    return r
